### PR TITLE
changed etcd operator storageclass from standard to default

### PR DESCRIPTION
**Pull request by hubvu**
- as discussed last week, I have changed the etcd operator storage class in the `values.yaml` configuration files from `standard` to `default`

### CODE REVIEW

**Comment by cvlc** [comment]
As it stands, this will only help if the user has a `StorageClass` called `default` and wants to use it for etcd operator. I chose `standard` as it seems to be a more conventional name for a default `StorageClass`. 

I'd argue that ideally we should leave this unset by default and use the actual default `StorageClass`, whatever it is. This would require a change to the etcd operator.

**Comment by cvlc** [comment]
The defaults for different platforms are:
* `standard` for GKE
* `gp2` for EKS
* `managed-csi` and `default` for AKS
* `standard` for upstream K8s

For that reason, I think that we should ideally use the class specified as default in metadata by default but `standard` is a good fallback and default value for the chart.

@Mojachieee curious what your perspective is on this!

**Comment by DavidMarchant** [comment]
Yes I agree with Calum, I think this is a change to be made in the operator, we shouldn't be stopped from using a cluster's actually default storageclass by the CR

**Comment by Mojachieee** [comment]
It seems to me that the operator should fallback to the default storage class if none is provided. I'm surprised it doesn't do this already

**Comment by hubvu** [comment]
@cvlc yes that makes sense - what I will do instead is to ensure that we ensure that `README.md` documentation clearly informs the user needs to add a storage class for etcd. I will go ahead and close this PR.

@Mojachieee yes I also thought about this too when I was testing out the helm charts, this is something that the kubectl plugin already does quite well

**Pull request closed without merging**
